### ISSUE TITLE
Conflicts in Lab 02 Decision Tree max_length

### ISSUE THREAD

**Issue by Luo-Chang** [uoe-iaml/iaml-labs#5]
There is a conflict that Q1.12 requires students to train a decision tree with max_length of 2, while Q1.17 refers to this setup as max_length of 3.

**Comment by yrluo** [comment]
The Q1.12 max_length should be set as 3. Otherwise, the downstream confusion matrices will be all 0s and 1s.

**Comment by macaodha** [comment]
Fixed.
